version: "3"
services: 
    web:
        build:
            context: .
            dockerfile: Dockerfile_django
        container_name: "web-django"
        ports: 
            - "8000:8000"
        volumes:
            - ".:/web-version/"
        # 下二行は-itと同じ役割
        tty: true
        stdin_open: true